### PR TITLE
Updated waiting screen removal logic

### PR DESCRIPTION
**Pull request by kennycoder**
image

### CODE REVIEW

**Comment by markmandel** [comment]
Taking for a spin, just to confirm everything works as expected 👍🏻

**Comment by markmandel** [comment]
Hmnn, getting errors when trying to compile this on Cloud Build:

If you want to take a look:
https://console.cloud.google.com/cloud-build/builds;region=global/b2ffbc56-1bba-4f6e-85a7-d7e32ab43981;step=1?jsmode=o&mods=logs_tg_prod&project=mark-world-scale

Oh wait I see it:

```
Step #1 - "build-image": LogInit: Display: LogAssetRegistry: Error: Package /tmp/project/Content/Player/DS_PlayerControllerBP.uasset is too new. Engine Version: 1008 Package Version: 1009
2023-07-19 12:33:41.894 PDT
Step #1 - "build-image": LogInit: Display: LogAssetRegistry: Error: Package /tmp/project/Content/MainGame/DS_GameModeBP.uasset is too new. Engine Version: 1008 Package Version: 1009
```

Did you upgrade your Unreal version?

**Comment by markmandel** [comment]
Just tried it locally as well - got the same result when trying to Cook the content (Unreal 5.1.0)

```
UATHelper: Cooking (Linux): LogShaderCompilers: Display: Compiling shader autogen file: ../../../../../../home/mark/workspace/global-multiplayer-demo/game/Intermediate/ShaderAutogen/VULKAN_SM5/AutogenShaderHeaders.ush
UATHelper: Cooking (Linux): LogShaderCompilers: Display: Autogen file is unchanged, skipping write.
UATHelper: Cooking (Linux): LogAssetRegistry: Error: Package /home/mark/workspace/global-multiplayer-demo/game/Content/MainGame/DS_GameModeBP.uasset is too new. Engine Version: 1008  Package Version: 1009
UATHelper: Cooking (Linux): LogAssetRegistry: Error: Package /home/mark/workspace/global-multiplayer-demo/game/Content/Player/DS_PlayerControllerBP.uasset is too new. Engine Version: 1008  Package Version: 1009
PackagingResults: Error: Package /home/mark/workspace/global-multiplayer-demo/game/Content/MainGame/DS_GameModeBP.uasset is too new. Engine Version: 1008  Package Version: 1009
PackagingResults: Error: Package /home/mark/workspace/global-multiplayer-demo/game/Content/Player/DS_PlayerControllerBP.uasset is too new. Engine Version: 1008  Package Version: 1009
```

**Comment by kennycoder** [comment]
Indeed Unreal version got updated. I was on master branch and with latest pull it bumped to 5.2.0. Needs full rebuild.

**Comment by markmandel** [comment]
> Indeed Unreal version got updated. I was on master branch and with latest pull it bumped to 5.2.0. Needs full rebuild.

Ah got it. Okay, then we need to update the whole toolchain then before we can test this. Probably a good reason to also implement #113 to make testing a bit easier (at least for me).

**Review by markmandel — APPROVED** [review]

**Pull request merged**
